# Copyright (C) 2023 Intel Corporation.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: compile wamrc

on:
  # will be triggered on PR events
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - ".github/workflows/build_wamrc.yml"
  # will be triggered on push events
  push:
    branches:
      - main
    paths:
        - ".github/workflows/build_wamrc.yml"
  # allow to be triggered manually
  workflow_dispatch:

# Cancel any in-flight jobs for the same PR/branch so there's only one active
# at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fetch_code_and_dependency:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: download dependencies
        run: |
            ./download.sh
            working-directory: runtime-library/deps

  build_llvm_libraries_on_ubuntu_2204:
    needs: [fetch_code_and_dependency]
    uses: ./.github/workflows/build_llvm_libraries.yml
    with:
      os: "ubuntu-22.04"
      arch: "X86"

  build_wamrc:
    needs:
      [build_llvm_libraries_on_ubuntu_2204]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            llvm_cache_key: ${{ needs.build_llvm_libraries_on_ubuntu_2204.outputs.cache_key }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      # since jobs.id can't contain the dot character
      # it is hard to use `format` to assemble the cache key
      - name: Get LLVM libraries
        id: retrieve_llvm_libs
        uses: actions/cache@v3
        with:
          path: |
            ./core/deps/llvm/build/bin
            ./core/deps/llvm/build/include
            ./core/deps/llvm/build/lib
            ./core/deps/llvm/build/libexec
            ./core/deps/llvm/build/share
          key: ${{ matrix.llvm_cache_key }}
          working-directory: ./runtime-library/deps/wamr-gc/wamr-compiler

      - name: Quit if cache miss
        if: steps.retrieve_llvm_libs.outputs.cache-hit != 'true'
        run: echo "::error::can not get prebuilt llvm libraries" && exit 1

      - name: Build wamrc
        run: |
          mkdir build && cd build
          cmake .. -DWAMR_BUILD_GC_BINARYEN=1
          cmake --build . --config Release --parallel 4
        working-directory: ./runtime-library/deps/wamr-gc/wamr-compiler
